### ISSUE TITLE
Small devices (iPhone 5) responsive issue

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#10]
On smaller phones, there seems to be some white space to the right side of the main container which causes an x-overflow.

![impact qualivera com_ iphone 5_se](https://user-images.githubusercontent.com/7881400/49245961-c1d5b700-f3e1-11e8-8a3c-6bca29fd1f1b.png)

**Comment by djsutter** [comment]
I can't reproduce in the browser, but if it's still an issue we will figure it out.
