### ISSUE TITLE
Mobile menu list items

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#11]
list items margin should be bigger for .menu-mobile-visible

Dev site
![impact qualivera com_ iphone 6_7_8](https://user-images.githubusercontent.com/7881400/49247110-812b6d00-f3e4-11e8-86bf-0f19d83a4f31.png)

html prototype
![loogart github io_impact-canada_ iphone 5_se](https://user-images.githubusercontent.com/7881400/49247187-aae49400-f3e4-11e8-8cdd-49146f758f03.png)

**Comment by djsutter** [comment]
It was actually line-height. Base theme differences.

**Comment by loogart** [comment]
Excellent!
