### ISSUE TITLE
Fix container positioning and width

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#16]
Note that the width of the container is wider than the About and how it works pages (which require .narrow css class). I guess I would like to have the ability to toggle the css class as a template for wider vs. narrow content. Let me know if this makes sense to you!

**Comment by djsutter** [comment]
This will take some template work. Not sure if we can allow customize, but probably need to base the narrow with on "basic page"

**Comment by djsutter** [comment]
This is done by setting max width on <main> for basic page. Unfortunately it ruins the Challenges page so will have to find a way around that. Might have to make a new content type such as "Basic Page Narrow" or maybe "Static Page". Ideas?

**Comment by loogart** [comment]
that's a good idea. We can have two templates: (1) basic page (regular .container) and (2) narrow basic page (.container .narrow). Would that work?

**Comment by loogart** [comment]
one thing i did notice, the challenges page (which we will remove anyways), has been affected.

<img width="1509" alt="screen shot 2018-12-08 at 6 57 38 pm" src="https://user-images.githubusercontent.com/7881400/49691919-41b6fc00-fb1b-11e8-870a-b1bc042c2f3c.png">

**Comment by djsutter** [comment]
Fixed!! Added a checkbox to Basic Page to indicate rendering in a narrow column. I set this flag on the About page (only).
![image](https://user-images.githubusercontent.com/22455573/49842040-066d3500-fd88-11e8-9c6b-edd821cdc0d1.png)

**Comment by loogart** [comment]
@djsutter OMG I am so excited for this. I had a tear of joy when I saw this graceful implementation you setup!!! 🎁
