### ISSUE TITLE
Ability to add news item

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#22]
News item doesn't need to be added from within the challenge. It can be setup as a new piece of content with a dropdown for the department / challenge owner name.

**Comment by djsutter** [comment]
Worked on the news page. More is required. We need images; I used placeholder boxes for now.
Questions:
- Are we removing current link from news item to challenge?
- Are we removing fields Sidebar and Type?

**Comment by djsutter** [comment]
Ok added the date and removed the two fields Sidebar and Type.
The column is already full width but the cards would need to be a bit thinner to get a fourth one in.
Lots of content updates needed by you guys before we go live! Images, dates...

**Comment by loogart** [comment]
@djsutter no need for a fourth column, leave it at 3 as per: https://loogart.github.io/impact-canada/news.html
(there is some padding/margin to the right of the columns)

**Comment by djsutter** [comment]
Ok sounds good. Let me know if anything else needed to complete this particular item, other than content changes.

**Comment by loogart** [comment]
@djsutter yes! On the challenge page (e.g. http://impact.qualivera.com/en/challenges/smart-cities), can you remove the "News" nav item (since they will all go to the news page)? thx!

**Comment by djsutter** [comment]
Done!

**Comment by loogart** [comment]
Ultra nice implementation! We love it. 
From a css standpoint, I added several lines of css for images under #newsContent which help the image resize automaticlly - that would need to be gulped in :)

Second, there seems to be drop shadow and bottom margin under the image missing:

**Qualivera version**
<img width="1034" alt="screen shot 2018-12-19 at 3 08 27 pm" src="https://user-images.githubusercontent.com/7881400/50245442-7723db00-03a0-11e9-9d3b-caa88d33e72a.png">

**Loogart version**
<img width="1275" alt="screen shot 2018-12-19 at 3 12 46 pm" src="https://user-images.githubusercontent.com/7881400/50245470-8efb5f00-03a0-11e9-806b-aa6e5b6465db.png">

**Comment by loogart** [comment]
ouh youre right, let me look at this now

**Comment by loogart** [comment]
@djsutter it looks like it's getting fixed when I add images. I have 1 more to add and the alternate solution is to add a placeholder image instead.

**Comment by loogart** [comment]
@djsutter looks like adding an image for each card works! One thing i noticed with the French), can we format the date to show up as "day month year" (no comma)? Currently, it is showing up as "month day, year"
<img width="373" alt="screen shot 2018-12-20 at 7 42 30 am" src="https://user-images.githubusercontent.com/7881400/50285739-29a08000-042b-11e9-85a6-d86ed758cc50.png">
.

**Comment by djsutter** [comment]
Looking good! I will fix the FR date format when I get a moment and also look at the loop for rows. However, on that, I don't think we should be necessarily fixing it to 3 items per row for responsiveness. I've seen equal heights work well with a pile of items that aren't divvied up into rows.

**Comment by loogart** [comment]
sounds like a plan! site it looking real good. This is definitely a portfolio piece!

**Comment by djsutter** [comment]
FR date fixed, image is now mandatory.
