### ISSUE TITLE
Ability to edit navigation bar and footer items

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#23]
- Ability to add, edit and remove links in the header navigation and footer sections.
- .footer__right should have an html editor so that we can change the emoji image that appears on hover.

**Comment by djsutter** [comment]
- I will have to show you how to edit the menus in Drupal.
- Will make the right footer into a block so you can edit

**Comment by djsutter** [comment]
Right footer done, it's a block now.

**Comment by loogart** [comment]
awesome. You can show me how to edit menus in drupal when we ship the product!
