### ISSUE TITLE
Subpage container width

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#24]
Ability to select (dropdown) if subpage will require regular bootstrap .container or narrower (add .narrow class) layout.

**Comment by djsutter** [comment]
Is this fixed with #16 or is this for challenge sub-pages?

**Comment by loogart** [comment]
same as #16 :) again, I am ultra excited. It's a "Thriller Moment"!

![120806-1532336916](https://user-images.githubusercontent.com/7881400/49888494-20049000-fe0d-11e8-90b1-90b00d773066.jpg)

**Comment by djsutter** [comment]
You like that eh? 
I'm out at the office party but I enjoyed your emails!

⁣Sent from Blue ​
