### ISSUE TITLE
Homepage: Open / Close / Coming Soon

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#25]
Ability to select open, close or coming soon for each challenge which will reflect the color of the pill and quarter circle bullet.

Classes: 
`.sts` (status) 
`.blt` (bullet)

**Comment by djsutter** [comment]
First part done, you can set the status of each challenge.
![image](https://user-images.githubusercontent.com/22455573/49944975-bdb59900-feb9-11e8-8a89-f46995c63445.png)

**Comment by djsutter** [comment]
This is done, except I don't know what bullet colours you want. Check the home page, I made challenge #2 closed and #3 coming soon. We can change them back later.

**Comment by loogart** [comment]
that's perfect. The only one to change is the coming soon to .blt-navy. just like in the pic below.

![screen shot 2018-12-13 at 8 20 06 pm](https://user-images.githubusercontent.com/7881400/49977480-7f00fc80-ff14-11e8-8725-7573fb615a1c.png)

**Comment by djsutter** [comment]
Ok fixed that. This item should be done now.

**Comment by loogart** [comment]
This is epic. Love it.
