### ISSUE TITLE
Custom css overrides

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#26]
1. Can there be a place where we can add global css that will override the theme's css?
2. Is there also a possibility to add css override PER challenge? i.e. if a specific challenge has a specific style, can this more specific css be only applicable to the challenge-related pages?

**Comment by djsutter** [comment]
Will give this consideration. Ideally, you would be able to edit the theme directly and commit changes to github but there are process issues we would need to address. Such as how to get it to the server.

**Comment by loogart** [comment]
totally agree with you if that is the ideal. As far as css overrides per challenge, maybe we can simply keep the css inline for sake of simplicity (as it is right now), unless you can create challenge-specific css stylesheets.

**Comment by djsutter** [comment]
I have consolidated all the scss that has been accumulating during development, it's all in style.scss now. It is possible that there are regressions, so don't be surprised if something that was fixed gets broken again.
Also I will leave a file called override.css (currently empty) for override that does not require scss compile.
We can probably (hoepfully) address per-challenge css in the theme, but if not maybe we can figure out how to get it into the Drupal back-end editing.

**Comment by djsutter** [comment]
Thinking this through... we will need a process. Best option is if you can commit css changes to github and we pull them on the server. Also it allows us to test changes on the dev server and propagate them to production. For short term, immediate fixes, we can always go back to how you did it before using a block to hold global css overrides. I don't really prefer that, but it's an option.

**Comment by djsutter** [comment]
Would you be ok if you just email me when you need css pulled on the dev server? Or is it way better if you can pull them yourself. It is an option.

**Comment by djsutter** [comment]
Ok, yes this does make sense. The block still exists and just needs to be enabled and cleared of the previous CSS which is now obsolete. We cab also look at the ability to collaborate on the theme in github. Will need to work out a convention or process so that things work smoothly (e.g. always pull latest before you make changes).
