### ISSUE TITLE
Navigation bar (highlight color tabindex)

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#27]
Just noticed this, when using tab to navigate with the accessibility feature, the background color of the highlighted navigation item is light gray. We should remove this bg color and simply keep the usual blue rectangular halo around the selected item.

<img width="1347" alt="screen shot 2018-12-07 at 10 01 47 am" src="https://user-images.githubusercontent.com/7881400/49654954-3b376000-fa07-11e8-9954-5948f97d1db1.png">

**Comment by djsutter** [comment]
I've seen it and I think it might be fixed now by dumb luck. Probably from the scss consolidation that I just did.

**Comment by loogart** [comment]
hey duncan! still seeing it on Chrome Version 70.0.3538.110 (Official Build) (64-bit).

**Comment by djsutter** [comment]
Can you try a full refresh (probably CTRL-F5) or a cache clear? I tried it on exact same version of Chrome and it's ok for me. Or I'm missing something.

**Comment by loogart** [comment]
@djsutter still tried (with hard refresh), it's showing up on Chrome. I will try at work tomorrow as well just in case.

**Comment by djsutter** [comment]
Ok check now, I think we got it!
