### ISSUE TITLE
Jumbotron Heading Font

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#3]
jumbotron h1 needs to be adjusted to match the prototype. I believe there might be some css overriding issues, so the following should make it match... also the Roboto font is not kicking in for some reason.

`.jumbotron h1 {
    border-bottom: 0 !important;
    font-size: 2.8em;
    font-weight: 700;
    line-height: 1.11;
    font-family: Roboto;
}`

**Comment by djsutter** [comment]
Check it again. I made some changes so it is better now. Let me know if more tweaks needed.
