### ISSUE TITLE
Navbar active

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#31]
When a new top level page loads (about, how it works, etc...), the red bottom border pulses on load (the height pops up and goes back down to regular height. I'm not sure how to troubleshoot it. You will see it if you click from 1 page to another in the navigation bar.

nav.navigation-bar .navigation__items .menu a.is-active {
    border-bottom: 0.69rem solid #E25456;
    background-color: inherit;
}

**Comment by djsutter** [comment]
I did see this but not sure yet why it's happening.

**Comment by loogart** [comment]
it happens only in chrome. Upon inspecting the browser, the only difference I can notice is that my prototype has a `div.menu > a` and the qualivera version is built with `ul.menu.nav.navbar > li > a`. Another idea would be to add the property `border-bottom: 0.69rem solid transparent;` to the class `nav.navigation-bar .navigation__items .menu a`.

**Comment by djsutter** [comment]
Fixed it! It was transition: all 0.15s ease-out;
