### ISSUE TITLE
CTA on About page is narrow

### ISSUE THREAD

**Issue by djsutter** [loogart/impact-canada#32]
The pink CTA on the About page is the same with as the content. Need to work out a better structure where the node content is narrow and does not affect the other regions on the page.

**Comment by djsutter** [comment]
Fixed with #16 
We can associate either CTA with any page using the block assignment. I can show you, or tell me which pages should have which CTA (pink or blue)

**Comment by loogart** [comment]
@djsutter hey I have several (4) variations LOL of the CTA button. Can we add variations 3 and 4 to the mix? And I will definitely need to know how to add to blocks.

1. blue: https://loogart.github.io/impact-canada/
2. pink: https://loogart.github.io/impact-canada/about.html
3. very dark: https://loogart.github.io/impact-canada/how-it-works.html
4. navy blue: https://loogart.github.io/impact-canada/news.html

**Comment by djsutter** [comment]
Do you want me to add the new blocks or show you how to do it? it's something we could do over the phone.

**Comment by djsutter** [comment]
Did this. I'll have to show you another day how it works.

**Comment by loogart** [comment]
Sounds good, I will mark it as closed!
