### ISSUE TITLE
minor css updates

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#36]
- fixed mobile version of challenge navigation (removed scroll bar on mobile)

**Comment by djsutter** [comment]
I found your css change and added it to the scss, but not sure if it's working. Anyway, I see this is for Rel 2.1

**Comment by loogart** [comment]
works like a charm! It simply removed the scroll bar on the tabs on mobile.

![screen shot 2018-12-17 at 7 57 40 pm](https://user-images.githubusercontent.com/7881400/50125275-0bbdfa00-0236-11e9-92e5-741696611dc3.png)
