### ISSUE TITLE
Subpage template design

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#38]
I will need to design a subpage template (the current one, based on the old template now has an unstyled banner and header text/links.

WIll get that to you asap. I will be merging some content this morning to get ahead of the curve while maneuvering my way around other design tasks, but you should hear from me soon RE subpage template @djsutter !

**Comment by djsutter** [comment]
Ok sounds good.

**Comment by loogart** [comment]
@djsutter I created a simple subpage template (essentially I added breadcrumbs within the container section since I would like to control the width i.e. narrow vs full width like in the basic page template). Remove sidebar as well. This affects the custom.scss file as well (extra css for the breadcrumbs). merci!

**Comment by loogart** [comment]
Yes. default the wide container (like the basic page) with an option to do narrow.

**Comment by loogart** [comment]
@djsutter also noticed some challenges like Smart Cities use the sidebar. Is there a way to copy paste the sidebar content into the page as html and I will format with columns after the fact?

http://impact.qualivera.com/en/challenges/smart-cities/applicant-guide

**Comment by djsutter** [comment]
I never noticed that before. I'm not sure, this might get tricky as I see they're using a 2-col panel page layout. But if you can describe what would be ideal I can see what I can do. Also, could we not just edit that page in Drupal and move the text out of the sidebar content box?

**Comment by loogart** [comment]
I think i will edit those now before you proceed to build the new subpage template. I will put it into a bootstrap column. Once I am done all subpages, I will confirm here! That cool?

**Comment by djsutter** [comment]
Yup!

**Comment by djsutter** [comment]
Subpage template is done, and I added the narrow checkbox to the content type. The only thing is that the narrow view is not constrained properly on the right side. Will fix tomorrow.

**Comment by djsutter** [comment]
I'm done for tonight. Pick it up again tomorrow morning.

**Comment by djsutter** [comment]
Fixed the narrow rendering. All done, I think.

**Comment by loogart** [comment]
all done for sure! that's great and works like a charm with breadcrumbs.
I guess the only thing will be the css to grab (custom.scss) later to reduce the breadcumb size to match https://loogart.github.io/impact-canada/subpage.html
