### ISSUE TITLE
CTA Blocks for French pages

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#41]
Hey duncan, how do I get the CTA boxes on About, partner etc pages to appear at the bottom?

**Comment by djsutter** [comment]
Ok I can show you, see how this goes...
Go into Structure > Block layout. Scroll to bottom.
For CTA pink, click on the Configure button.
In the Configure block page, half way down, click on the Pages tab. You will see a textarea containing "/about". That makes the pink CTA show up on the About page.
Add more pages to whatever CTA blocks you want to show up on what page. No need to treat EN or FR differently. Wildcards are allowed.

**Comment by loogart** [comment]
@djsutter the block configuration has changed. All the blocks (all colours) have been configured to <front> for homepage, yet they all show up properly. I found this while I was trying to fix the CTA block for the French homepage.

**Comment by djsutter** [comment]
I don't understand the problem. I see only one configured for homepage (front)

**Comment by loogart** [comment]
Morning! Was my error, i updated the FR blue CTA block!
Sorry about that.
