### ISSUE TITLE
Home button on challenge page

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#42]
When clicking on the home button (top left) from a challenge page, it goes to the "challenges" standalone page which we are phasing out.

E.g. http://impact.qualivera.com/fr/defis/villes-intelligentes

brings you to

http://impact.qualivera.com/fr/defis

**Comment by djsutter** [comment]
So long ago... can you check this again to see if still a problem?

**Comment by loogart** [comment]
works like a charm! thank you!
