### ISSUE TITLE
Ability to rename Summary/description tab

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#44]
Hey Duncan, we would need to be able to edit/add the Summary/description **TITLE** of this section which shows up as the first tab on the challenge page.

Example:

<img width="1034" alt="screen shot 2018-12-19 at 2 44 18 pm" src="https://user-images.githubusercontent.com/7881400/50243953-9882c800-039c-11e9-980c-03bef0da898e.png">

<img width="884" alt="screen shot 2018-12-19 at 2 42 18 pm" src="https://user-images.githubusercontent.com/7881400/50243882-6a9d8380-039c-11e9-9a6d-ebaf7e7778fa.png">

**Comment by djsutter** [comment]
Do you mean rename "The Challenge" as shown above?

**Comment by loogart** [comment]
yes. Need to add a title for the description/summary box. (just like challenge subpages have a title which appear on the challenge navigation tabs!
Thanks!

**Comment by djsutter** [comment]
Ok have a look at the challenge pages now and see if they're working as wanted. The changes are temporary so if it's ok then I will make them permanent in the source code. Then I can look at how to give you control to rename "Home" to whatever you like.

**Comment by loogart** [comment]
Awesome. thank you for the insanly quick turnaround!
I noticed something I might try to fix from my end on the css (the flexbox implementation for the challenge nav looks less interesting for 2 tabs, see image below) - ill create another issue for myself and which might require a new css gulp.

<img width="945" alt="screen shot 2018-12-19 at 3 35 46 pm" src="https://user-images.githubusercontent.com/7881400/50246616-e2bb7780-03a3-11e9-833b-d8c707f60bfd.png">

**Comment by djsutter** [comment]
Roger that!

**Comment by djsutter** [comment]
Ok this is done. The field is called "Nav Title" and it's mandatory. Of course, existing challenge pages don't have a value. The default is "Home" (Accueil).
Currently I have set the Nav title for the Crush It challenge to be "Main page" (english only). Since it's a mandatory field, I will leave as-is and let you fix it.

**Comment by loogart** [comment]
that is #boss. AWESOME! thank you.
