### ISSUE TITLE
Challenge page: Back to all Challenges translation

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#46]
Hey @djsutter , is there a way i can easily translate the "back to challenges" for FR?

<img width="474" alt="screen shot 2018-12-19 at 7 48 17 pm" src="https://user-images.githubusercontent.com/7881400/50256995-207dc780-03c7-11e9-9f44-51bb3a160b9d.png">

**Comment by djsutter** [comment]
I just made that a translatable string. Do you know how to do translations? I did know, but this site is different, so I've been looking.
Anyway, I've see hard-coded English strings all over the place and sometimes I make them translatable.

**Comment by djsutter** [comment]
Found it. http://impact.qualivera.com/en/admin/config/regional/translate
Search for the English term then provide the French translation.
Let me know what others you find are missing and I will fix.

**Comment by loogart** [comment]
yes!!! thanks D.
