### ISSUE TITLE
Heading 2 and p.lead

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#5]
Styling needs to be updated to match font sizes and colors + the quarter circle in front of h2 is missing.

<img width="1021" alt="screen shot 2018-11-29 at 10 51 10 am" src="https://user-images.githubusercontent.com/7881400/49233769-b3c56d80-f3c4-11e8-90d5-11448aaf9f54.png">

<img width="1029" alt="screen shot 2018-11-29 at 10 50 47 am" src="https://user-images.githubusercontent.com/7881400/49233750-a7411500-f3c4-11e8-98cc-f3eb044ab9c7.png">

**Comment by djsutter** [comment]
Fixed. Also affected a view.

**Comment by loogart** [comment]
@djsutter hey! can you adjust the color of the h2 and p to the navy blue?
Font is good though!

**Comment by djsutter** [comment]
Done.
