### ISSUE TITLE
Regulp css

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#51]
styling items to fix, 

- [x] **1. Subpage Breadcrumbs styling**

![screen shot 2018-12-21 at 6 07 54 am](https://user-images.githubusercontent.com/7881400/50339899-c96f1400-04e6-11e9-946c-80ce0d9d856f.png)

- [x] **2. Extra space on the right side of cards on mobile**

![impact qualivera com_ iphone 6_7_8](https://user-images.githubusercontent.com/7881400/50339982-118e3680-04e7-11e9-9093-2771192f36eb.png)

- [x] **3. Extra space on the right side of news items mobile**

![screen shot 2018-12-21 at 6 15 05 am](https://user-images.githubusercontent.com/7881400/50340143-d6d8ce00-04e7-11e9-9db3-24daf9b50938.png)

**Comment by djsutter** [comment]
it's taking me a bit too long to figure out where your changes are for 2 and 3. Can you just let me know which parameters to change?
BTW our scss files have diverged a fair bit - not drastically, but enough that it's getting hard to spot differences.

**Comment by loogart** [comment]
Hey D, I know that the previous versions of the staging site were fine for points 2-3, but let me take a look. Wouldn't it be simpler to grab my custom.scss file? I always update it on Github - unless there are extra things you have added?

**Comment by djsutter** [comment]
I do have a copy of your repo and I pull occasionally and am able to compare your scss with mine. For the longest time I left yours alone and just added my own overrides but this became harder to manage. Now I just edit my scss as needed. So they're getting more different all the time. It's all because of how Drupal themes are constructed. Your structures are nice and simple but with drupal templates they become a bit more complicated sometimes. That's the problem.

**Comment by djsutter** [comment]
If you like, I can send you mine if you want to compare them

**Comment by loogart** [comment]
sounds good. I’ll still try to find the styling difference via browser first and if I can get it fixed simply, I’ll send the aces code. Otherwise I’ll ask for the scss to compare.

**Comment by loogart** [comment]
@djsutter man, i am stumped LOL. this is my friday night challenge!

**Comment by djsutter** [comment]
Do you ever look at your previous commits in github? I've done that a few times to see what you changed. Just need to remember when it was

**Comment by djsutter** [comment]
Ok I made the change. Seems ok to me.

**Comment by djsutter** [comment]
Oh yes, news items on full view. Can probably fix that.

**Comment by loogart** [comment]
cool, it actually works in French (the english one is not full view)

**Comment by djsutter** [comment]
I did a width 100% if width > 767. Does that work? I'm not sure I like the images stretching like that.

**Comment by loogart** [comment]
works for news (i assume images stretch because of the lack of support by IE for the css object-fit css property).

But for desktop, (i know it's annoying, please don't hate me!) the homepage items are a bit off. 
Can we simply remove the width:100% from the .wb-eqht?

![screen shot 2018-12-21 at 5 42 05 pm](https://user-images.githubusercontent.com/7881400/50366463-d3752f00-0547-11e9-97f6-9fb6cc526e8d.png)
![screen shot 2018-12-21 at 5 41 56 pm](https://user-images.githubusercontent.com/7881400/50366464-d3752f00-0547-11e9-88dd-4291b2b60864.png)

**Comment by loogart** [comment]
(once this is fixed, I think we should push it on the live server and i can test stuff out next week when it's calm)

**Comment by djsutter** [comment]
Ok I made the change. Can I push it to the live server tomorrow?

**Comment by loogart** [comment]
would be great.

I really think the english news page is trying to annoy us before the weekend...
http://impact.qualivera.com/en/news (this is narrow for some reason)
**VS**
http://impact.qualivera.com/fr/news (this is the right look)

**Comment by djsutter** [comment]
Starting the upgrade of the live server now. Not sure if I have a non-pco email for you so I'm doing it through this thing.

**Comment by djsutter** [comment]
It is done. We can look at fixing the news page and anything else.

**Comment by loogart** [comment]
![Duncan, cheers to you!](
https://i.giphy.com/media/g9582DNuQppxC/giphy.webp)
Upgrade complete :)

Yes, there is only the width of the English news to fix next week

http://impact.qualivera.com/en/news (this is narrow for some reason)
VS
http://impact.qualivera.com/fr/news (this is the right look)
