### ISSUE TITLE
News page EN only

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#55]
On the English News page, at a media query min-width: 1200px, the row which contains all the news items becomes narrow and aligned to the left. Happens only on Chrome and Safari. On IE, everything looks good.

The french page doesn't have the same effect. 

need to investigate and fix.

**Comment by djsutter** [comment]
I spent an hour looking at this in the first week of January, and still can't quite explain it. I did detailed comparison of the HTML structure and the CSS, and they are identical. My best guess is that the French text is such that it has crossed some threshold which causes the columns to go full width.

I set the width of div #wb-auto-1 to 100% and it is working, but I'm not sure if it affects anything else in the site. Have a look around and if everything looks ok then I guess we're done with this one.

**Comment by loogart** [comment]
@djsutter let's close this. Rodney has requested something new regarding this section, so @habernation and I will be working on building this. Thanks for the help on this.
