### ISSUE TITLE
Updated News page template

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#58]
We've updated the Challenge News content type on the DEV site as follows:
- Challenge field changed to "field_parent_challenge" for consistency with Challenge Subpage content type
- Created a URL link field (field_url)
- Renamed Department field to Source

**The PRESS content type on the dev site should be removed (I can't seem to delete it)**

**Proposed revisions to the News page**:
Chris prepared a mock-up:
https://loogart.github.io/impact-canada/news.html#

Notable changes to the page:
- Simplified (no body text shown)
- Parent Challenge instead of department should be shown
- The Published Date is simplified
- No longer a 'read more' button
- smaller tiles

We would like the user to be redirected to whatever URL is entered in the field_url field (whether they click the image or the title). We'd also like to limit the length of the title and add "..." in the event it exceeds 3/4 lines in the compressed view.

Chris has is set to change to 2 and then 1 column as the window is resized.

**Comment by djsutter** [comment]
I updated the news template on the dev site. You will see that the layout breaks because it's not doing equal heights. Even if we trim the title length, it won't fix it. BTW for trim length we need #chars.
Suggest we might want to try flex layout with fixed-width cards.

**Comment by loogart** [comment]
@djsutter i can redesign with flexbox. but i don't understand the diff between the html prototype i created and the dev site. I assume you updated the css as well since it looks the same. Sometimes the web has a way of hurting my brain.

**Comment by loogart** [comment]
@djsutter actually, i you add the wet css class to the parent div `row news-cards wb-eqht` it should work. I took it out, but just add the `wb-eqht`. let me know!

**Comment by djsutter** [comment]
I did try that. All the cards went really thin.

**Comment by loogart** [comment]
ill look into it

**Comment by loogart** [comment]
@djsutter here is the fix, works on all browsers. I updated the css which you can pull. the main code to update is the p.department and the h2.

   ```
&#newsContent {
        .news-cards {
            a {
                text-decoration: none;
            }

            img {
                margin-bottom: $space-md;
                object-fit: cover;
                width: 100%;
                height: 190px;
            }

            p.department {
                color: $red;
                font-weight: 500;
                margin-bottom: $space-sm;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }

            h2 {
                margin-bottom: $space-sm;
                color: $navy-blue;
                margin-top: 0;
                font-size: 1.25em;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }

            p.small {
                color: slategray;
                font-weight: 500;
            }
        }
```

**Comment by djsutter** [comment]
I think you nailed that sucker! Check it out...

**Comment by loogart** [comment]
Looks good to me!
