### ISSUE TITLE
Homepage card widths

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#60]
@djsutter once the page loads on mobile, the following id `#wb-auto-1` seems to remove the 100% width of the the cards on the homepage. This happens on mobile and desktop see images below. 

![screen shot 2019-01-24 at 10 21 05 am](https://user-images.githubusercontent.com/7881400/51688092-da1d1900-1fc1-11e9-8ff7-d331cce1dca0.png)

![impact canada ca_ iphone 5_se](https://user-images.githubusercontent.com/7881400/51687958-8f030600-1fc1-11e9-81de-4a9a5c234189.png)

**Comment by loogart** [comment]
@djsutter hey any update on this item?

**Comment by djsutter** [comment]
Hey. Sorry did not get a chance to work on the weekend, buried in accounting (that time of year).
Check the dev site now, I just removed the 100% width. Not sure why it was added Jan 16th, but maybe for reasons which no longer exist.

**Comment by loogart** [comment]
perfect! that is ready to be merged to live.

**Comment by djsutter** [comment]
Done. Just waiting for the cache to clear.
