### ISSUE TITLE
Create new status "In selection"

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#64]
Hey @djsutter, we were asked to add a new "in selection" status which affects the homepage. Each challenge already has "open", "closed" and "coming soon". Can you create the in-selection status with the new css i added (which will also be selectable from the Challenge page)?

See: https://loogart.github.io/impact-canada/

**Comment by djsutter** [comment]
Hey @loogart I will be working this evening and will see how much of this I can get done. The first software update succeeded so I'm happy about that. I haven't applied it in production yet but hope I can soon.

**Comment by djsutter** [comment]
I see that the prod site already has "In Selection" status. Since I pulled the css change, is this now complete?

**Comment by loogart** [comment]
@djsutter hey duncan, the Crush it challenge is "In Selection", but I don't see the status bullet or the quarter circle beside the title on the home

<img width="1201" alt="screen shot 2019-02-01 at 10 18 35 am" src="https://user-images.githubusercontent.com/7881400/52131433-c3527400-260a-11e9-90fd-a85f46a44dbb.png">
page.

**Comment by djsutter** [comment]
Ok, we should try to get these things resolved in the dev site, but I will have a look when I get a moment. Hopefully just a quick fix.

**Comment by djsutter** [comment]
This is done. Now that you have access to the theme in github, you may be interested in looking at my commits.
