### ISSUE TITLE
Update PROD site with new content type and new challenge status ICON

### ISSUE THREAD

**Issue by habernation** [loogart/impact-canada#65]
HI Duncan- we've made the following updates to the DEV site:

- Added a new status "In Selection" for Challenges that are not open for applications but are still active (see issue #64)
- Added a 'Juror' role, dashboard, and block 
- Added 'Restricted Page' content type that allows for upload of documents to the private folder
- Updated custom blocks

These are all ready for moving to PROD. 

Thanks!

**Comment by loogart** [comment]
@habernation same as this: https://github.com/loogart/impact-canada/issues/64

**Comment by djsutter** [comment]
I am going to update the production site shortly. If you have any block content that needs to get moved, it would have to be done manually. I'll let you know when this is done...

**Comment by habernation** [comment]
Hi- I deleted the Shortcut links and sets on both the DEV and PROD sites (except the one called default). We don't really need them and they haven't been working very well anyway.

Let me know if that helps

**Comment by djsutter** [comment]
Ok yes that helped, the config is now imported. You might be interested in these warnings which seem related to missing block content:

>  [notice] Synchronized configuration: create views.view.challenge_judging_page.
>  [warning] The "block_content:afe92301-cbb3-4004-9e40-a4c8bb1e6c73" was not found
>  [notice] Synchronized configuration: create block.block.cssblockuserdashboards.
>  [warning] The "block_content:0b67aa00-e624-41bb-a505-6fbab151b5a8" was not found
>  [notice] Synchronized configuration: create block.block.challengeownermenu_2.
>  [warning] The "block_content:0b67aa00-e624-41bb-a505-6fbab151b5a8" was not found
>  [notice] Synchronized configuration: create block.block.challengeownermenu.
>  [warning] The "block_content:799c0fae-6a24-4efe-a531-41d4ceefdc51" was not found
>  [notice] Synchronized configuration: create block.block.challengejurormenu_2.
>  [warning] The "block_content:975e8dec-9297-4542-ac96-be26bf811053" was not found
>  [notice] Synchronized configuration: create block.block.challengeadminmenu_2.
>  [warning] The "block_content:975e8dec-9297-4542-ac96-be26bf811053" was not found
>  [notice] Synchronized configuration: create block.block.challengeadminmenu.
>  [notice] Synchronized configuration: update block.block.impact_bootstrap_local_tasks.
>  [notice] Synchronized configuration: update block.block.impact_bootstrap_local_actions.
>  [warning] The "block_content:afe92301-cbb3-4004-9e40-a4c8bb1e6c73" was not found

**Comment by habernation** [comment]
Hi Duncan - one thing that did not seem to translate to the PROD is the PRIVATE file system. The PROD site isn't configured to allow file uploads to a private folder.  Do you think this can be done by tomorrow morning? I am supposed to have about twenty files uploaded and accessible for a few users tomorrow mid-day.

**Comment by djsutter** [comment]
Ok sure I will get on that shortly and will let you know.

**Comment by djsutter** [comment]
The private filesystem has been created in production. Give it a shot, it should work.

**Comment by habernation** [comment]
Looks like it's working! Thanks Duncan!
Have a nice weekend,
Mike
