### ISSUE TITLE
Challenge subpage titles

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#67]
@djsutter this is a minor semantic issue, but probably easy to fix and can be done whenever.
Can we make all challenge subpage titles h2 (instead of h1) since the Challenge title in the "jumbotron" area is already an h1?

E.g. 
https://impact.canada.ca/en/challenges/off-diesel/initiative (title is highlighted)

![screen shot 2019-02-07 at 3 04 55 pm](https://user-images.githubusercontent.com/7881400/52439541-c2798080-2ae9-11e9-8dfd-44e3e784c6ab.png)

**Comment by djsutter** [comment]
This is done on the dev site impact.qualivera.com
Note that the bottom margin for h2 in this context is larger than the previous h1

**Comment by loogart** [comment]
That is no problem (thanks for pointing it out), somedays I feel my ui needs more spacing, somedays, i feel it needs less. I just feel better (in my gut) that the structure of headings is good.

You can push this to the live site!

**Comment by djsutter** [comment]
Ok done!
