### ISSUE TITLE
Card fonts and .sts-open status pills

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#7]
Fonts need to be updated to match prototype and there is a white line under the .sts-open (make viewport a bit narrower and it appears)

<img width="988" alt="screen shot 2018-11-29 at 10 54 52 am" src="https://user-images.githubusercontent.com/7881400/49234022-3ea66800-f3c5-11e8-9324-ed486efe56bf.png">
<img width="982" alt="screen shot 2018-11-29 at 10 54 42 am" src="https://user-images.githubusercontent.com/7881400/49234023-3ea66800-f3c5-11e8-9a95-b7d28dda1db8.png">

**Comment by djsutter** [comment]
Check it now. I cannot reproduce.
