### ISSUE TITLE
RUSH: Challenge Details Title Editable

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#70]
Hi @djsutter, this just in. Indigenous Services are very sensitive when it comes to using the term Challenge. 

Can you setup a field to edit the Challenge Details Title (e.g. if it is left blank = defaults to "Challenge Details" otherwise if we fill out the field we can change it to something else)? It's the 2nd time we are requested to do so, so i figured that I wouldn't use javascript to change the inner HTML this time LOL

Thank you. it's relatively rush since they want this to be changed for their launch tomorrow.

**Comment by djsutter** [comment]
Hi @loogart , just got in the door. Will have a look and see what I can do quickly.

**Comment by loogart** [comment]
awesome thanks Duncan

**Comment by djsutter** [comment]
This is getting to be a big deal, I'm having to change module code in addition to templates. Will have to pick it up later, it's been an hour now.

**Comment by djsutter** [comment]
Almost working but not quite.

**Comment by loogart** [comment]
@djsutter temporary backup solution, I am using js to change the inner html. Once you have found the final solution, we can implement it after the fact. No need to rush it, I would rather let you have a glass of scotch than work on this for hours tonight!

**Comment by djsutter** [comment]
Thanks. It's good that you have a backup solution. I will still try to finish the override, but it is fairly complicated and touches a few areas. Will let you know how it goes.

**Comment by djsutter** [comment]
I got the fix ready. Would you like me to jam it into production?

**Comment by loogart** [comment]
push it! let me know how it works as well (i checked the Qualivera version, but didn't see a new field!)

**Comment by djsutter** [comment]
Oh I didn't put it on the Qualivera site. I'll do that now. Should be about 5 mins. Then I will do production.

**Comment by djsutter** [comment]
Need a little more time. I realized that the field needs to be translatable, so doing that now...

**Comment by djsutter** [comment]
Sorry. I'm having nothing but trouble now. Still trying.

**Comment by djsutter** [comment]
Ok got it working on Qualivera site. Had to disable workflow/revisions, it's messed up with French translation. Feel free to try it on something other than Crush It, and see how it works for you.

**Comment by loogart** [comment]
awesome ready to go!

**Comment by djsutter** [comment]
ok I just tested it in production, looks good. resetting my test now. You can try

**Comment by loogart** [comment]
Looks like it works like a charm. Awesome stuff Duncan, thanks! @djsutter

**Comment by djsutter** [comment]
Yay! good stuff, thanks.
