### ISSUE TITLE
Replace DEV site with the PROD site

### ISSUE THREAD

**Issue by habernation** [loogart/impact-canada#74]
We are ready to replace the dev site with the current public Impact.Canada.ca site. *** Please do not copy anything that is in the private file system to your dev site - it contains confidential business information that cannot be on your server ****.

**Comment by djsutter** [comment]
Ok, I'll get on that later today probably.

**Comment by djsutter** [comment]
This is complete now. I also exported the latest config (lots of changes) and stored in github.
Now we're in a good position to make all structural changes in dev and propagate to production.

**Comment by djsutter** [comment]
Assume it's ok to close this issue.
